# Exported from Render on 2026-05-07T09:10:23Z
version: "1"
services:
  - type: web
    name: fliplearn
    runtime: python
    repo: https://github.com/Uttama786/classroom
    plan: free
    region: oregon
    buildCommand: |
      pip install torch==2.5.1 --index-url https://download.pytorch.org/whl/cpu --no-cache-dir &&
      pip install -r requirements.txt --no-cache-dir &&
      python manage.py collectstatic --noinput
    startCommand: python manage.py migrate_with_retry --max-retries 30 && python manage.py create_admin && gunicorn flipped_classroom_project.wsgi:application --workers 1 --threads 4 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: GROQ_API_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DATABASE_URL
        fromDatabase:
          name: fliplearn-db
          property: connectionString
    autoDeployTrigger: commit
    rootDir: flipped_classroom_project
